### ISSUE TITLE
Data availability?

### ISSUE THREAD

**Issue by StuntsPT** [gibsonMatt/pimpGEA#1]
Hi @gibsonMatt ,
I have just read your paper "[Regional differences in the abiotic environment contribute to genomic divergence within a wild tomato species](https://doi.org/10.1111/mec.15477)", which is really nice! I'd like to include some of the data there in a meta-study I am currently working on.
Unfortunately, the DOI given for dryad is a 404 error. Can you please let me know where to find the data?
Thank you very much in advance!

Francisco

**Comment by gibsonMatt** [comment]
Hey Francisco,
Funny that you emailed me today. I was just notified that the Dryad repo was still set to private/under peer review. It should be live in the next few days.

-Matt

On Aug 10, 2020, at 12:21 PM, Francisco Pina-Martins <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi @gibsonMatt<https://github.com/gibsonMatt> ,
I have just read your paper "Regional differences in the abiotic environment contribute to genomic divergence within a wild tomato species", which is really nice! I'd like to include some of the data there in a meta-study I am currently working on.
Unfortunately, the DOI given for dryad is a 404 error. Can you please let me know where to find the data?
Thank you very much in advance!

Francisco

**Comment by StuntsPT** [comment]
Awesome!
Thank you for the instant reply!

**Comment by gibsonMatt** [comment]
https://datadryad.org/stash/dataset/doi:10.5061/dryad.8gtht76k4
